// ---------------------------------------------------------------------------
// Zotero library reorganisation -- Corentin Ravoux
//
// Paste into Zotero: Tools > Developer > Run JavaScript, tick "Run as async
// function", press Run.  Read the report it prints before trusting it.
//
// BACK UP FIRST: quit Zotero, copy
//   ~/snap/zotero-snap/common/Zotero/zotero.sqlite
// somewhere safe, then reopen Zotero.
//
// Set DRY_RUN = false only once the dry run looks right.
// The script is idempotent: running it twice changes nothing the second time.
// ---------------------------------------------------------------------------

const DRY_RUN = true;          // <-- flip to false to apply
const REMOVE_OLD = true;       // remove items from their previous collections
const DELETE_EMPTIED = false;  // delete old collections left empty (do by hand first time)

const LIB = Zotero.Libraries.userLibraryID;
const PAYLOAD = {
"paths": [
"Meta",
"Meta/Writing and community",
"Methods",
"Methods/EFT and perturbative modelling",
"Methods/Emulators and machine learning",
"Methods/Estimators and numerics",
"Methods/Field-level inference",
"Methods/Statistics and compression",
"Probes",
"Probes/21 cm",
"Probes/CMB",
"Probes/Clusters and cosmic web",
"Probes/Galaxies and emitters",
"Probes/Galaxy clustering and BAO",
"Probes/Gravitational waves",
"Probes/Lyman alpha",
"Probes/Lyman alpha/3D correlations and BAO",
"Probes/Lyman alpha/IGM and absorbers",
"Probes/Lyman alpha/P1D",
"Probes/Lyman alpha/Tomography",
"Probes/Peculiar velocities",
"Probes/Quasars and AGN",
"Probes/Supernovae",
"Probes/Voids",
"Probes/Weak lensing",
"Resources",
"Resources/Books",
"Resources/Reviews and lectures",
"Resources/Software",
"Resources/Theses",
"Simulations",
"Simulations/Boltzmann and linear theory",
"Simulations/Hydrodynamical and IGM",
"Simulations/N-body, ICs and codes",
"Simulations/Neutrino simulations",
"Surveys",
"Surveys/DESI",
"Surveys/Euclid",
"Surveys/Future spectroscopic",
"Surveys/Gaia and stellar",
"Surveys/Other facilities",
"Surveys/Rubin LSST",
"Surveys/SDSS BOSS eBOSS",
"Surveys/ZTF",
"Theory",
"Theory/Black holes",
"Theory/Dark energy",
"Theory/Dark matter",
"Theory/Foundations",
"Theory/Inflation and non-Gaussianity",
"Theory/Modified gravity",
"Theory/Neutrinos",
"Theory/Tensions and anomalies"
],
"assign": {
"5LXJFIU8": "Simulations/N-body, ICs and codes",
"M9WSNKLK": "Simulations/N-body, ICs and codes",
"FEMY2IUY": "Probes/Lyman alpha/IGM and absorbers",
"9GKPDILC": "Probes/Lyman alpha/IGM and absorbers",
"VSSFI8DX": "Probes/Lyman alpha/3D correlations and BAO",
"3IR5RDCN": "Simulations/Hydrodynamical and IGM",
"KPGP35GA": "Simulations/Hydrodynamical and IGM",
"B3D387W5": "Probes/Lyman alpha/IGM and absorbers",
"EY64XFFZ": "Probes/Galaxy clustering and BAO",
"J7HMB6FY": "Probes/Voids",
"H9AJ34SS": "Probes/Lyman alpha/Tomography",
"437UYELS": "Probes/Voids",
"R3M2J652": "Probes/Quasars and AGN",
"WHN45F42": "Probes/Lyman alpha/Tomography",
"XQN65SPT": "Probes/Lyman alpha/3D correlations and BAO",
"LYBBATKA": "Probes/Lyman alpha/P1D",
"AUA4GDMH": "Surveys/SDSS BOSS eBOSS",
"ABMI57Z8": "Simulations/Neutrino simulations",
"S7SJM2BE": "Probes/Lyman alpha/IGM and absorbers",
"92PE97XD": "Probes/Lyman alpha/3D correlations and BAO",
"C7H349UN": "Probes/Lyman alpha/IGM and absorbers",
"ZEWA5EGN": "Probes/Lyman alpha/Tomography",
"Y8J95ZKR": "Theory/Black holes",
"FJ4BEYFB": "Theory/Black holes",
"8KQEIEGD": "Theory/Black holes",
"P5UYXKUQ": "Theory/Dark matter",
"8BTCGCX7": "Resources/Reviews and lectures",
"6JFS43U2": "Resources/Books",
"C3N9KECA": "Resources/Books",
"BE62VKR2": "Resources/Books",
"IYBS9H97": "Resources/Books",
"45BN2QK2": "Resources/Books",
"BZ2SR5E2": "Probes/CMB",
"6R6FCZJS": "Probes/Lyman alpha/P1D",
"MH9QPDUN": "Probes/Lyman alpha/P1D",
"QWR48KFB": "Surveys/DESI",
"ED54XXC3": "Probes/Lyman alpha/IGM and absorbers",
"LBM54B7Q": "Probes/Lyman alpha/IGM and absorbers",
"D9QUN3BY": "Probes/Lyman alpha/IGM and absorbers",
"4HRQMYAK": "Probes/Lyman alpha/3D correlations and BAO",
"Y6IXBFLQ": "Probes/Lyman alpha/3D correlations and BAO",
"3NN4RDVX": "Probes/Lyman alpha/IGM and absorbers",
"K2W6PXGU": "Probes/Lyman alpha/P1D",
"I2V2B5IH": "Simulations/Hydrodynamical and IGM",
"5U2GM8XH": "Probes/Lyman alpha/IGM and absorbers",
"IWX8WIJ3": "Probes/Quasars and AGN",
"S586EE5Q": "Theory/Neutrinos",
"ML6LLSZ2": "Theory/Neutrinos",
"6UVI9VYD": "Resources/Reviews and lectures",
"3EIDJ7E8": "Simulations/Neutrino simulations",
"875WUP2Q": "Simulations/Neutrino simulations",
"5ZZEJ5CC": "Simulations/Neutrino simulations",
"78YAJNMJ": "Resources/Reviews and lectures",
"DFG2T232": "Simulations/Neutrino simulations",
"WD7N7PWK": "Resources/Reviews and lectures",
"HZD2I2LI": "Simulations/Neutrino simulations",
"KE49YKWN": "Simulations/Neutrino simulations",
"JVU6TS5U": "Probes/Lyman alpha/P1D",
"K7BHWA2H": "Theory/Neutrinos",
"4M9IWXJT": "Simulations/Neutrino simulations",
"MBECX3T4": "Simulations/Neutrino simulations",
"RT24HJA9": "Probes/Lyman alpha/P1D",
"ZSFYPUCP": "Theory/Neutrinos",
"F6R6HM4M": "Theory/Neutrinos",
"BRAXGL5B": "Simulations/Neutrino simulations",
"DD7U4FMP": "Theory/Neutrinos",
"XAI45ZFA": "Theory/Neutrinos",
"JGMV5Q2N": "Probes/Clusters and cosmic web",
"Y9H3T83Y": "Resources/Theses",
"F6TBX4Y7": "Resources/Theses",
"D3AGHMZ8": "Probes/Lyman alpha/Tomography",
"UBNQYXV2": "Probes/Lyman alpha/Tomography",
"KGVVIE9C": "Probes/Lyman alpha/Tomography",
"K4PVWQ5N": "Probes/Lyman alpha/Tomography",
"UT9RCQS2": "Probes/Lyman alpha/Tomography",
"JGCQHVVY": "Probes/Lyman alpha/Tomography",
"BS78522W": "Probes/Lyman alpha/Tomography",
"5323TXRS": "Probes/Lyman alpha/Tomography",
"YB37I9LK": "Probes/Lyman alpha/Tomography",
"USPP9MU5": "Probes/Lyman alpha/Tomography",
"BP47ZLAB": "Probes/Lyman alpha/Tomography",
"3WNSYMRT": "Probes/Voids",
"66RUSB3Q": "Simulations/Hydrodynamical and IGM",
"Q5LZCA3U": "Simulations/Hydrodynamical and IGM",
"H2YPL2EX": "Theory/Neutrinos",
"RHNFB9NK": "Probes/Lyman alpha/IGM and absorbers",
"CAJIVRRC": "Probes/Lyman alpha/IGM and absorbers",
"EZCTU3N5": "Probes/Lyman alpha/IGM and absorbers",
"SSE87CCN": "Probes/Lyman alpha/IGM and absorbers",
"K9G7QQYU": "Probes/Lyman alpha/IGM and absorbers",
"28UY5934": "Probes/Lyman alpha/IGM and absorbers",
"8EBA56WL": "Methods/Emulators and machine learning",
"YTEAPPL7": "Probes/Lyman alpha/3D correlations and BAO",
"G4BPGP7Y": "Probes/Lyman alpha/3D correlations and BAO",
"43IHMIIA": "Simulations/Hydrodynamical and IGM",
"E9KPMGEL": "Simulations/Hydrodynamical and IGM",
"RY3DTF5M": "Probes/Lyman alpha/3D correlations and BAO",
"NT3NBLIE": "Probes/Lyman alpha/P1D",
"GIALKR85": "Probes/Lyman alpha/Tomography",
"9DDDJAL7": "Simulations/N-body, ICs and codes",
"C8NCXQXQ": "Probes/Lyman alpha/Tomography",
"R9YADU74": "Probes/CMB",
"8AYTGUXV": "Methods/Emulators and machine learning",
"CWF7RU44": "Probes/Weak lensing",
"LLXTJ7CA": "Probes/Peculiar velocities",
"S98UYZA9": "Probes/Supernovae",
"BNDFEAB9": "Probes/Lyman alpha/P1D",
"X33EX9QZ": "Surveys/SDSS BOSS eBOSS",
"QQKNSR6A": "Theory/Foundations",
"EL2T2SGZ": "Simulations/N-body, ICs and codes",
"G6TQ5ESK": "Simulations/N-body, ICs and codes",
"EZZMGYPS": "Probes/Lyman alpha/Tomography",
"62HYBANS": "Theory/Foundations",
"XZI344X6": "Theory/Foundations",
"BFGI5S9F": "Probes/Voids",
"MR6A5Z7Q": "Theory/Foundations",
"CSJA3UK4": "Surveys/SDSS BOSS eBOSS",
"N428WVBF": "Probes/Quasars and AGN",
"JNYC73QU": "Probes/Galaxy clustering and BAO",
"TBCWF8VP": "Surveys/Euclid",
"B7SG8RRX": "Probes/Supernovae",
"9A3DEND4": "Surveys/SDSS BOSS eBOSS",
"PXW5UL96": "Probes/Quasars and AGN",
"Q5FN2EQD": "Simulations/N-body, ICs and codes",
"BCUKMK3T": "Surveys/DESI",
"PXEYIDLE": "Surveys/SDSS BOSS eBOSS",
"CV2VTLKR": "Surveys/SDSS BOSS eBOSS",
"S4SDF8DG": "Methods/Field-level inference",
"2WBQWTQC": "Probes/Voids",
"VNEANELD": "Probes/Voids",
"MJFQ8QGK": "Probes/Voids",
"LHEP5JIQ": "Probes/Quasars and AGN",
"J9F64X5U": "Surveys/SDSS BOSS eBOSS",
"YHTAWNSC": "Probes/Voids",
"D3TYYUT9": "Theory/Foundations",
"P46WXBN7": "Surveys/SDSS BOSS eBOSS",
"K26IWWDG": "Probes/Lyman alpha/Tomography",
"8GSFPLLY": "Probes/Voids",
"L8YUQXH6": "Probes/Voids",
"QVZWN25E": "Theory/Foundations",
"CJFLCKBL": "Probes/Voids",
"27M94T45": "Probes/Voids",
"DXP9J7G2": "Probes/Voids",
"XADMGNRH": "Probes/Voids",
"Q8LAVLSX": "Probes/Voids",
"PB7TP3AT": "Theory/Foundations",
"7EXHL46E": "Probes/Voids",
"MJ9I9QAU": "Probes/Voids",
"TDCYBLCN": "Probes/Voids",
"9RNHFP6T": "Probes/Galaxy clustering and BAO",
"JCQ6BHA8": "Surveys/DESI",
"JAGNFGEQ": "Probes/Peculiar velocities",
"EQ35E259": "Probes/Peculiar velocities",
"I7CNA4DC": "Probes/Peculiar velocities",
"67GBPNPU": "Probes/Lyman alpha/P1D",
"RQC7CXFD": "Theory/Tensions and anomalies",
"MF3X8ZPE": "Theory/Tensions and anomalies",
"DIP5TLVU": "Meta/Writing and community",
"87YAZ965": "Theory/Tensions and anomalies",
"AB486QAY": "Theory/Neutrinos",
"MKMEC5WH": "Theory/Tensions and anomalies",
"LKVX6L5V": "Theory/Tensions and anomalies",
"DN6AJ55H": "Resources/Books",
"35Z4I8WH": "Resources/Books",
"FEVQ6RUP": "Methods/Emulators and machine learning",
"JE4CV3DN": "Resources/Theses",
"WAY8PB7Q": "Resources/Theses",
"TKSHQSDB": "Resources/Theses",
"MR3QZRQZ": "Resources/Theses",
"TURI57DN": "Resources/Theses",
"IAH6T6LT": "Probes/CMB",
"JBY7HDV3": "Probes/Quasars and AGN",
"7UDZIT8S": "Probes/Lyman alpha/P1D",
"T65IFQBH": "Probes/Lyman alpha/IGM and absorbers",
"DGJWSGDM": "Probes/Lyman alpha/IGM and absorbers",
"ZGKHSVYJ": "Probes/Weak lensing",
"L5ZK4WT3": "Theory/Neutrinos",
"UMSIK3IT": "Probes/Supernovae",
"R5MT24FF": "Theory/Neutrinos",
"B4FTU2PE": "Theory/Neutrinos",
"GBTPLRU8": "Theory/Dark matter",
"9946I23A": "Probes/Clusters and cosmic web",
"ERUWIPVJ": "Simulations/N-body, ICs and codes",
"H6FD6CNE": "Probes/Lyman alpha/Tomography",
"C2N9M55U": "Probes/Lyman alpha/P1D",
"H32JV7W4": "Probes/Clusters and cosmic web",
"NMJR6V9L": "Simulations/Boltzmann and linear theory",
"XVM7FFM7": "Theory/Dark matter",
"LVA64GR2": "Theory/Dark matter",
"X79496UK": "Theory/Dark matter",
"4NI9RFX8": "Theory/Dark matter",
"X3MPLX35": "Theory/Dark matter",
"3G7R3BFT": "Theory/Dark matter",
"N64C4FMC": "Theory/Dark matter",
"65N64SY4": "Theory/Dark matter",
"SEFV6BP3": "Probes/Lyman alpha/P1D",
"6D5RURXN": "Theory/Dark matter",
"MH43DFZ5": "Theory/Neutrinos",
"ZGDQEAGB": "Theory/Neutrinos",
"MKTUEBT9": "Probes/Galaxy clustering and BAO",
"QXW9DSCW": "Probes/Supernovae",
"YLL9TX2B": "Resources/Books",
"WBRJGJIM": "Resources/Books",
"TQ3U24SA": "Resources/Books",
"DC84DAUL": "Theory/Foundations",
"G4WFNVRE": "Theory/Dark matter",
"C2D6E5RY": "Probes/Weak lensing",
"GUNHIRD8": "Probes/CMB",
"FAKYWURD": "Probes/CMB",
"25YDW7ZH": "Probes/CMB",
"E6G36E6W": "Probes/CMB",
"FZQHQLJL": "Surveys/Euclid",
"PSWYLXEE": "Probes/Supernovae",
"QCA4VMJ9": "Probes/Lyman alpha/IGM and absorbers",
"GREV3V6N": "Resources/Theses",
"EMIFAZZ2": "Resources/Theses",
"AFFR9VXX": "Probes/Lyman alpha/3D correlations and BAO",
"D2858KPL": "Surveys/SDSS BOSS eBOSS",
"ATBW49DJ": "Surveys/DESI",
"MNKYFZP7": "Surveys/DESI",
"F7Z476F9": "Surveys/DESI",
"SKQJEXMI": "Surveys/DESI",
"IBTEDML4": "Surveys/DESI",
"NKNTWGXJ": "Surveys/DESI",
"I54HUETN": "Surveys/DESI",
"9582QR38": "Surveys/DESI",
"TBLVKJ3I": "Surveys/DESI",
"L9KKLFM5": "Methods/Estimators and numerics",
"83TXACK9": "Methods/Estimators and numerics",
"Z5ZD6LDW": "Theory/Dark matter",
"9CWKJT37": "Surveys/SDSS BOSS eBOSS",
"GPC5LQW7": "Probes/Lyman alpha/Tomography",
"4IYU35ZU": "Surveys/Gaia and stellar",
"MXKA9S3F": "Surveys/DESI",
"8VYTMHX6": "Surveys/DESI",
"DYHCJ7F9": "Probes/Lyman alpha/Tomography",
"FGANB7UK": "Probes/Lyman alpha/IGM and absorbers",
"T4N7CE97": "Probes/Quasars and AGN",
"FKEJRCFS": "Probes/Quasars and AGN",
"LQM9L8DH": "Probes/Quasars and AGN",
"6NRDUDD4": "Probes/Lyman alpha/IGM and absorbers",
"DPUH9NNI": "Probes/Quasars and AGN",
"D65CB3AG": "Probes/Quasars and AGN",
"SHIAG46J": "Probes/Quasars and AGN",
"2CCWDARW": "Probes/Quasars and AGN",
"WWRL694V": "Probes/Quasars and AGN",
"ZAHCK76G": "Probes/Lyman alpha/IGM and absorbers",
"MBUAPZ9G": "Probes/21 cm",
"VTFV6QR3": "Probes/Lyman alpha/IGM and absorbers",
"97UTT7I9": "Probes/Lyman alpha/P1D",
"457IYTIL": "Resources/Reviews and lectures",
"HV96564S": "Probes/Lyman alpha/IGM and absorbers",
"SY3VWWAU": "Probes/Lyman alpha/3D correlations and BAO",
"YKQ5SJWZ": "Probes/Lyman alpha/P1D",
"KTACPEZ5": "Probes/Lyman alpha/IGM and absorbers",
"5NXZJPKG": "Probes/Quasars and AGN",
"HC8NLI5G": "Probes/Lyman alpha/IGM and absorbers",
"HQSWDFFT": "Probes/Lyman alpha/IGM and absorbers",
"RBLVNGAR": "Surveys/Other facilities",
"L68U5HL6": "Surveys/Future spectroscopic",
"KYEH47QM": "Probes/Lyman alpha/IGM and absorbers",
"V7GIMMK4": "Probes/Lyman alpha/IGM and absorbers",
"KYJSYE74": "Probes/Lyman alpha/IGM and absorbers",
"DQWQYIAS": "Probes/Lyman alpha/IGM and absorbers",
"HK5Q8FAP": "Probes/Lyman alpha/P1D",
"EP5MLF2W": "Probes/Lyman alpha/IGM and absorbers",
"BQDUYFFY": "Probes/Lyman alpha/IGM and absorbers",
"EN5RTRAA": "Probes/Lyman alpha/IGM and absorbers",
"PT7SCJGN": "Methods/Emulators and machine learning",
"J62JN62T": "Simulations/N-body, ICs and codes",
"FDH8AVLS": "Methods/Emulators and machine learning",
"JSYNGUHD": "Probes/Lyman alpha/Tomography",
"XI3W3NAI": "Probes/Lyman alpha/IGM and absorbers",
"F4QTZEJL": "Probes/Lyman alpha/IGM and absorbers",
"8ZKY99EN": "Probes/Lyman alpha/P1D",
"X7HZ6PMN": "Probes/Lyman alpha/P1D",
"HQV8VZW8": "Surveys/Other facilities",
"V5I3PRDK": "Probes/Lyman alpha/P1D",
"IVGNSZGK": "Probes/Lyman alpha/P1D",
"2H3PRXH6": "Probes/Lyman alpha/P1D",
"QZQZQ7MH": "Probes/Lyman alpha/P1D",
"3GFCA5IJ": "Probes/Lyman alpha/P1D",
"6L8SXHH6": "Resources/Theses",
"5SG527XP": "Resources/Theses",
"V492ED5I": "Surveys/Other facilities",
"55UWNV3S": "Probes/21 cm",
"WXMHDDR6": "Probes/Lyman alpha/Tomography",
"6LLZGDTG": "Probes/Lyman alpha/Tomography",
"VL7F4L2F": "Probes/Lyman alpha/Tomography",
"ZYLMYQTM": "Probes/Lyman alpha/Tomography",
"755QT3F8": "Methods/Estimators and numerics",
"5HXZKUPG": "Methods/Estimators and numerics",
"TLQH7EMF": "Surveys/SDSS BOSS eBOSS",
"2BCS4MP9": "Probes/Quasars and AGN",
"CYX7F6KZ": "Methods/Emulators and machine learning",
"IFXZUKG9": "Probes/Lyman alpha/IGM and absorbers",
"CEAIQXKC": "Probes/Lyman alpha/3D correlations and BAO",
"XR3ZII9U": "Probes/Lyman alpha/Tomography",
"KT2KWGRU": "Probes/Lyman alpha/IGM and absorbers",
"7IAG3D2B": "Probes/Lyman alpha/IGM and absorbers",
"5T8RBMUD": "Probes/Lyman alpha/IGM and absorbers",
"4ZS3VCDB": "Probes/Lyman alpha/IGM and absorbers",
"93LY24HW": "Surveys/Future spectroscopic",
"DCBY3DQL": "Surveys/Future spectroscopic",
"32GNI3DE": "Probes/Lyman alpha/3D correlations and BAO",
"CXJDYDQS": "Probes/21 cm",
"HBKYL73R": "Resources/Software",
"3ENI9QPZ": "Simulations/Hydrodynamical and IGM",
"8JVR7QUM": "Probes/Quasars and AGN",
"KFYM3L43": "Probes/Quasars and AGN",
"XJE53NH6": "Simulations/Hydrodynamical and IGM",
"ZGL4X3Z3": "Simulations/N-body, ICs and codes",
"V2T53Y52": "Simulations/Hydrodynamical and IGM",
"CYNGRB6X": "Simulations/N-body, ICs and codes",
"7IAXV2AD": "Simulations/Hydrodynamical and IGM",
"2UY2P3HD": "Simulations/N-body, ICs and codes",
"FAXFBQAT": "Simulations/N-body, ICs and codes",
"LTH22ZGX": "Simulations/Neutrino simulations",
"MFHVJJ3B": "Simulations/Neutrino simulations",
"Y3CKNQSB": "Probes/Lyman alpha/IGM and absorbers",
"DP85YJWC": "Probes/Lyman alpha/IGM and absorbers",
"AZH3K5HV": "Probes/Lyman alpha/IGM and absorbers",
"8NNHE6CK": "Simulations/N-body, ICs and codes",
"WM9GNC6C": "Simulations/Hydrodynamical and IGM",
"8D9LGSGU": "Simulations/Boltzmann and linear theory",
"Y2KIMWEK": "Simulations/Boltzmann and linear theory",
"L5UEM23J": "Simulations/Boltzmann and linear theory",
"LQHQ74WI": "Simulations/N-body, ICs and codes",
"IWLDP2QQ": "Probes/Lyman alpha/P1D",
"KRVBVINK": "Simulations/Hydrodynamical and IGM",
"WBCFAZ25": "Methods/Emulators and machine learning",
"5YLVLIVG": "Methods/Emulators and machine learning",
"8YNEIA6R": "Probes/Lyman alpha/IGM and absorbers",
"GRNY2TTQ": "Probes/Lyman alpha/P1D",
"7KGDB5CZ": "Probes/Lyman alpha/IGM and absorbers",
"I2SIL532": "Simulations/Hydrodynamical and IGM",
"YBPC2AKX": "Probes/Lyman alpha/Tomography",
"B2XKAYVP": "Resources/Software",
"73GXV9MJ": "Simulations/N-body, ICs and codes",
"PRZHUU3B": "Simulations/Hydrodynamical and IGM",
"SNKYE8HU": "Probes/Lyman alpha/IGM and absorbers",
"K5RRKX9R": "Surveys/SDSS BOSS eBOSS",
"WUDYEIV9": "Probes/Lyman alpha/P1D",
"BXEKTGC8": "Methods/Emulators and machine learning",
"U6AALMTM": "Probes/Lyman alpha/IGM and absorbers",
"YICIDNMQ": "Probes/Lyman alpha/Tomography",
"I36EMP3U": "Simulations/Hydrodynamical and IGM",
"Q2ZPQTX4": "Probes/CMB",
"VP3DRB8J": "Probes/CMB",
"6LQTS6HM": "Simulations/Hydrodynamical and IGM",
"I2LU8JYC": "Probes/Supernovae",
"C4W9NLZE": "Theory/Dark matter",
"9Y6L4I2C": "Theory/Foundations",
"VY32ZXH2": "Surveys/Future spectroscopic",
"UIPH2QTQ": "Surveys/Future spectroscopic",
"3STGIUHD": "Resources/Software",
"9ZXD7CQC": "Probes/Lyman alpha/IGM and absorbers",
"HI38N75J": "Surveys/Other facilities",
"JH7B7BNZ": "Probes/Voids",
"IHXED6DP": "Surveys/DESI",
"28ZZCQ9T": "Surveys/DESI",
"94WPC2ET": "Probes/Lyman alpha/IGM and absorbers",
"C8SJMB5K": "Resources/Reviews and lectures",
"2QS7IMR5": "Probes/Quasars and AGN",
"79JFU28R": "Methods/Estimators and numerics",
"KFTR8EAB": "Probes/Quasars and AGN",
"PGZFLEJ2": "Probes/Voids",
"F8HZDNBI": "Resources/Reviews and lectures",
"ETNEVCD6": "Theory/Neutrinos",
"N29YLR29": "Probes/Lyman alpha/IGM and absorbers",
"6APUQPZ8": "Simulations/Hydrodynamical and IGM",
"X6MM4M4F": "Probes/Lyman alpha/P1D",
"FJM4CKM4": "Probes/Lyman alpha/Tomography",
"UJXUHE7U": "Simulations/Hydrodynamical and IGM",
"95N3T8SP": "Probes/Clusters and cosmic web",
"BER8EEGM": "Probes/Quasars and AGN",
"S6DLNK8E": "Methods/Statistics and compression",
"YBKVE7P4": "Theory/Foundations",
"F8E35K7I": "Theory/Foundations",
"UL9G3NVT": "Theory/Foundations",
"YJ2V2HFD": "Simulations/Hydrodynamical and IGM",
"E4QR9NUL": "Simulations/Hydrodynamical and IGM",
"LRUQ2CS4": "Simulations/Hydrodynamical and IGM",
"R5H4VTH6": "Simulations/Hydrodynamical and IGM",
"UV8JPEPZ": "Simulations/Hydrodynamical and IGM",
"LKM2WT3I": "Simulations/Hydrodynamical and IGM",
"HWITGXFK": "Probes/Lyman alpha/P1D",
"SX5KFLPX": "Probes/Lyman alpha/3D correlations and BAO",
"FTY49MG7": "Probes/Voids",
"K9ZJRQDW": "Theory/Neutrinos",
"UCSRLKNS": "Surveys/DESI",
"3TQCV5N4": "Surveys/DESI",
"89U3NP8Q": "Surveys/DESI",
"QKYP62GF": "Surveys/DESI",
"QC5PCHMC": "Surveys/DESI",
"FJ9QTQ8V": "Surveys/DESI",
"LHBFIWX8": "Surveys/DESI",
"8ZDG2NVY": "Surveys/DESI",
"HZN25D5P": "Resources/Theses",
"L6UFH85J": "Resources/Books",
"CZ62B8GT": "Resources/Theses",
"9X77KR2U": "Probes/Peculiar velocities",
"T6GUNFR4": "Resources/Reviews and lectures",
"ETGXKYQD": "Methods/Statistics and compression",
"A3SMT386": "Methods/EFT and perturbative modelling",
"JHGI3RWR": "Resources/Theses",
"ZL345LPT": "Probes/Lyman alpha/P1D",
"QW9JGH8P": "Surveys/Future spectroscopic",
"RCSZXZWV": "Probes/Peculiar velocities",
"FVKZSKV5": "Probes/Supernovae",
"JZMHWNS6": "Probes/Peculiar velocities",
"C2AEBSSK": "Simulations/N-body, ICs and codes",
"7JJJUWZY": "Methods/Emulators and machine learning",
"J7EAD9LD": "Probes/Peculiar velocities",
"88KCJFZG": "Probes/Galaxies and emitters",
"L53E7Q9X": "Probes/Galaxies and emitters",
"7T62K9TR": "Probes/Galaxies and emitters",
"GEY778KT": "Methods/Statistics and compression",
"SM8WV6KF": "Probes/Peculiar velocities",
"CG55YGTA": "Probes/Peculiar velocities",
"IGMKEMNI": "Probes/Peculiar velocities",
"94ZDMUDV": "Probes/Lyman alpha/P1D",
"LXQI3LJN": "Probes/Lyman alpha/IGM and absorbers",
"WUMHPD2J": "Probes/Lyman alpha/IGM and absorbers",
"TVFC46VQ": "Probes/Lyman alpha/P1D",
"92QPJAF8": "Probes/Lyman alpha/P1D",
"LH7UDCLL": "Probes/Lyman alpha/P1D",
"BVF7BZKK": "Probes/Lyman alpha/P1D",
"WIDJK78F": "Simulations/Hydrodynamical and IGM",
"M3ZRKVI8": "Methods/Field-level inference",
"48Y2F42Y": "Probes/Lyman alpha/P1D",
"DQ9TMZXD": "Probes/Lyman alpha/IGM and absorbers",
"DSIBN9YK": "Probes/Peculiar velocities",
"5JSXRQ9V": "Probes/Lyman alpha/P1D",
"3LSRS9FP": "Probes/Lyman alpha/IGM and absorbers",
"UHZQY4RQ": "Probes/Peculiar velocities",
"QSDI5PLX": "Probes/Peculiar velocities",
"JJ2HGXLF": "Probes/Peculiar velocities",
"6IDCEIAB": "Resources/Reviews and lectures",
"YNXYKSRV": "Methods/Emulators and machine learning",
"89HEEW3P": "Simulations/Hydrodynamical and IGM",
"S9I8AQMB": "Theory/Foundations",
"YVKVDPJZ": "Methods/Statistics and compression",
"7EF4Q7EH": "Probes/Peculiar velocities",
"T53B35RP": "Probes/Peculiar velocities",
"YCT99DPD": "Probes/Peculiar velocities",
"7TA7UIS9": "Probes/Lyman alpha/3D correlations and BAO",
"QQL4USRS": "Probes/Lyman alpha/3D correlations and BAO",
"TWRSUP59": "Theory/Black holes",
"FY3F3SUE": "Probes/Galaxy clustering and BAO",
"BPL27PAE": "Probes/Galaxy clustering and BAO",
"LMJVJLKJ": "Resources/Reviews and lectures",
"26JMU8AB": "Probes/Galaxy clustering and BAO",
"HATAZUUT": "Methods/Field-level inference",
"IAJXEQ82": "Probes/Galaxy clustering and BAO",
"TRYKBJED": "Surveys/Future spectroscopic",
"RD4IRTDI": "Surveys/Future spectroscopic",
"Y5DXAP7P": "Surveys/Future spectroscopic",
"7PGZMXZF": "Probes/CMB",
"DNLESPUX": "Probes/CMB",
"YHSN5QF5": "Probes/CMB",
"L6BQF6RL": "Probes/CMB",
"JNKPAVAF": "Probes/CMB",
"MKTMQPMF": "Probes/CMB",
"K8KLNYMM": "Probes/CMB",
"MFLCEEGH": "Theory/Dark matter",
"L3WCMEZT": "Theory/Modified gravity",
"TPK545MC": "Theory/Black holes",
"C8AS34X9": "Probes/Lyman alpha/IGM and absorbers",
"8CMT5JU2": "Probes/Lyman alpha/3D correlations and BAO",
"JZTD8GCF": "Probes/Lyman alpha/3D correlations and BAO",
"3NW2MEBH": "Probes/Lyman alpha/IGM and absorbers",
"BLTPA9C7": "Probes/Lyman alpha/IGM and absorbers",
"W6II2TN2": "Surveys/Other facilities",
"A8D6SW3K": "Probes/Lyman alpha/3D correlations and BAO",
"U6RA3269": "Theory/Dark matter",
"ZDD7Q2ER": "Theory/Dark matter",
"8SJ48NWK": "Probes/Lyman alpha/3D correlations and BAO",
"UXNZGNM9": "Probes/Lyman alpha/IGM and absorbers",
"73R2PT8R": "Probes/Lyman alpha/3D correlations and BAO",
"JHRJY38J": "Probes/Lyman alpha/IGM and absorbers",
"XBTPHEHY": "Probes/Lyman alpha/IGM and absorbers",
"PE932HUP": "Surveys/Other facilities",
"AIA7Q5RF": "Surveys/Other facilities",
"DJUK8J86": "Surveys/Other facilities",
"5LW9ZK5F": "Surveys/Other facilities",
"SFEPLL2U": "Theory/Neutrinos",
"6L5J672D": "Theory/Neutrinos",
"BRC5JE4R": "Simulations/Neutrino simulations",
"BT7XEEDF": "Simulations/Neutrino simulations",
"H8BFQVG9": "Simulations/Neutrino simulations",
"2VYUK573": "Theory/Neutrinos",
"H2K6NCE9": "Theory/Neutrinos",
"AB89RX2B": "Probes/Lyman alpha/P1D",
"GQSA9K8Q": "Resources/Reviews and lectures",
"YXHFEXUG": "Surveys/SDSS BOSS eBOSS",
"MPVZD3DQ": "Surveys/SDSS BOSS eBOSS",
"SVXJWQN3": "Methods/Emulators and machine learning",
"YZ9C2CHA": "Simulations/Hydrodynamical and IGM",
"7A8DKAIX": "Simulations/N-body, ICs and codes",
"9BMRT9EB": "Simulations/Hydrodynamical and IGM",
"G59G6PV2": "Simulations/N-body, ICs and codes",
"3JJKS8WN": "Simulations/Hydrodynamical and IGM",
"NRYB52ZI": "Simulations/N-body, ICs and codes",
"BB8IE2RK": "Simulations/Hydrodynamical and IGM",
"MZ9GFLQI": "Simulations/Hydrodynamical and IGM",
"HXVXDRVL": "Probes/Clusters and cosmic web",
"2XQXFH8K": "Probes/Clusters and cosmic web",
"M2XZRHYJ": "Resources/Theses",
"8XT7HRWM": "Probes/Lyman alpha/Tomography",
"4QYKQKFK": "Probes/Lyman alpha/Tomography",
"A4NH32IV": "Probes/Lyman alpha/Tomography",
"TLF58MSJ": "Probes/Lyman alpha/Tomography",
"7D2NZMBW": "Probes/Lyman alpha/Tomography",
"JQ8JN6E5": "Probes/Lyman alpha/Tomography",
"565M7KYE": "Probes/Voids",
"TGMIFAEZ": "Probes/Voids",
"Y3GJ8K3H": "Probes/Weak lensing",
"IN55KLND": "Surveys/DESI",
"V5UWHR42": "Meta/Writing and community",
"HKZPIGQP": "Surveys/DESI",
"EHMECJGA": "Surveys/DESI",
"4IW6LLWV": "Surveys/DESI",
"X4CF87UE": "Surveys/DESI",
"HIXTGCRB": "Surveys/DESI",
"YIT6YHCD": "Surveys/DESI",
"8MZ4IS8C": "Simulations/Hydrodynamical and IGM",
"T273WBZV": "Resources/Reviews and lectures",
"NCRT9KEA": "Probes/Peculiar velocities",
"C4CN89BZ": "Probes/Peculiar velocities",
"IDPCXSD2": "Probes/Peculiar velocities",
"RE9X78BE": "Probes/Peculiar velocities",
"WV8TN5W8": "Probes/Peculiar velocities",
"QD9DE469": "Probes/Lyman alpha/P1D",
"SEBHDYRW": "Probes/Lyman alpha/P1D",
"BKKB9D3A": "Theory/Foundations",
"L6FESPZ4": "Methods/EFT and perturbative modelling",
"N94PHRX6": "Probes/Peculiar velocities",
"P5N7DALJ": "Methods/EFT and perturbative modelling",
"YRPN6I46": "Methods/EFT and perturbative modelling",
"22E3X9QT": "Methods/EFT and perturbative modelling",
"NAQM8W2X": "Methods/EFT and perturbative modelling",
"PTCEWXN5": "Resources/Theses",
"TD4ZE5W2": "Probes/Supernovae",
"8G4JEUYZ": "Probes/Supernovae",
"BWRMNR5V": "Probes/Supernovae",
"43W98PBA": "Probes/Supernovae",
"H6RYZS6P": "Probes/Supernovae",
"TDGA3WVQ": "Probes/Supernovae",
"TVW5SEZY": "Probes/Supernovae",
"A5399BS4": "Methods/EFT and perturbative modelling",
"MXGECNXG": "Theory/Foundations",
"CQUMMP4J": "Probes/Peculiar velocities",
"AG48RJLW": "Probes/Peculiar velocities",
"TUUHM9CF": "Probes/Galaxy clustering and BAO",
"JGYPW7R3": "Simulations/Hydrodynamical and IGM",
"JHFB6ICT": "Probes/Lyman alpha/P1D",
"VB7WXRJK": "Probes/21 cm",
"JTDYPS3H": "Probes/Lyman alpha/IGM and absorbers",
"VEN3UTKL": "Probes/Supernovae",
"4SGCMZSB": "Surveys/Rubin LSST",
"U76UJLD6": "Surveys/Rubin LSST",
"HII6NQK6": "Surveys/Rubin LSST",
"YTDPKXCB": "Methods/Estimators and numerics",
"VJZ6DXL8": "Probes/Supernovae",
"RBLIGRHU": "Probes/CMB",
"2BQMCKW6": "Probes/Supernovae",
"P95X7W3Z": "Probes/Galaxy clustering and BAO",
"7WUQ8Z8B": "Meta/Writing and community",
"GFK2W8D4": "Probes/Peculiar velocities",
"RAB33TSX": "Probes/Galaxy clustering and BAO",
"2RJ24IPS": "Surveys/DESI",
"PEB7NMU8": "Probes/Lyman alpha/P1D",
"LDFZ7D9S": "Resources/Theses",
"9MH7LBRT": "Probes/Peculiar velocities",
"WVYDTVFW": "Probes/Peculiar velocities",
"YIEG27XX": "Probes/Peculiar velocities",
"J3DPMD7A": "Probes/Peculiar velocities",
"U4DT4EMT": "Probes/CMB",
"Y64YX6KI": "Probes/Supernovae",
"7YCQ4Z93": "Surveys/Rubin LSST",
"Z2AKIPWI": "Methods/Field-level inference",
"QDKZ3J7N": "Theory/Dark energy",
"GY2HQDJC": "Probes/Lyman alpha/IGM and absorbers",
"ELBCUVLY": "Probes/Supernovae",
"IIGPLFAF": "Probes/Supernovae",
"J2H28Y8P": "Probes/Supernovae",
"ZS9C5KC6": "Surveys/Rubin LSST",
"7Z6JYRNX": "Resources/Theses",
"A3PNRUPM": "Surveys/Rubin LSST",
"A4EPL2LK": "Probes/Supernovae",
"IXMN8923": "Surveys/ZTF",
"NGIJ667B": "Probes/Supernovae",
"ZEF6TX9X": "Probes/Supernovae",
"RR375HFD": "Surveys/Future spectroscopic",
"XCEIK8Q5": "Surveys/Future spectroscopic",
"NJHYNG9N": "Surveys/Future spectroscopic",
"4EHVKSG4": "Probes/Galaxy clustering and BAO",
"RIH8GKNB": "Theory/Dark matter",
"XD88ZTNR": "Theory/Dark matter",
"Y2LC26BP": "Theory/Dark matter",
"45DVHZ29": "Probes/Clusters and cosmic web",
"4VEWP8ZB": "Probes/Lyman alpha/Tomography",
"6N5J3QB6": "Probes/Supernovae",
"7FNJAAZT": "Probes/Peculiar velocities",
"DIRR687U": "Surveys/Future spectroscopic",
"CKJ6UUM9": "Surveys/Gaia and stellar",
"T5T9W4H8": "Methods/Statistics and compression",
"QJA9IF9K": "Probes/Galaxy clustering and BAO",
"97GCXFQE": "Surveys/Euclid",
"I7B788JK": "Probes/Supernovae",
"B6J2TVPN": "Surveys/Rubin LSST",
"P4JYKMNM": "Surveys/Rubin LSST",
"ZA7347EQ": "Surveys/Gaia and stellar",
"ZSK5GK9V": "Surveys/Gaia and stellar",
"7BTDNUIX": "Probes/Peculiar velocities",
"82X73YVE": "Methods/Field-level inference",
"ESWS2YGL": "Surveys/ZTF",
"FMFXVZTQ": "Surveys/DESI",
"8N7PLVGD": "Surveys/DESI",
"JRHUJN6A": "Probes/Peculiar velocities",
"JS6UGRYT": "Probes/Peculiar velocities",
"H4TE7X9V": "Probes/Supernovae",
"CIFFW4XU": "Surveys/Gaia and stellar",
"TPZYQX58": "Probes/Lyman alpha/IGM and absorbers",
"4YJ5TG5Y": "Simulations/Hydrodynamical and IGM",
"T5PYJXL6": "Surveys/Other facilities",
"Q3E6CZ2K": "Theory/Dark matter",
"XXM3ISJ7": "Probes/Lyman alpha/P1D",
"LA8RZC97": "Theory/Dark matter",
"M996UUSU": "Simulations/Hydrodynamical and IGM",
"9MP9ANCU": "Simulations/Hydrodynamical and IGM",
"TSXM7IFN": "Probes/Peculiar velocities",
"HPPEULNP": "Surveys/DESI",
"X3RMSKNH": "Probes/Lyman alpha/IGM and absorbers",
"5I6JKNQ2": "Probes/Lyman alpha/P1D",
"Q8SDYQN2": "Probes/Supernovae",
"INYFPGFI": "Probes/Supernovae",
"9T2FREMB": "Meta/Writing and community",
"XGJCZFTG": "Probes/Peculiar velocities",
"3PMTCL43": "Probes/Peculiar velocities",
"K9S3D7KH": "Probes/Peculiar velocities",
"M63F2NFA": "Probes/Peculiar velocities",
"DMTBPIMV": "Probes/Peculiar velocities",
"TCXVNX8W": "Methods/EFT and perturbative modelling",
"HN32LXYV": "Methods/EFT and perturbative modelling",
"NC3QLNB3": "Methods/EFT and perturbative modelling",
"C8XXK3MJ": "Probes/Peculiar velocities",
"4CVGD34M": "Probes/Peculiar velocities",
"X9FMZ78D": "Probes/Peculiar velocities",
"5GBIQDIM": "Methods/Field-level inference",
"U4KNPFRS": "Probes/CMB",
"68EQH2BQ": "Probes/CMB",
"WNK36XG3": "Probes/Peculiar velocities",
"3Q3LLMFZ": "Theory/Dark matter",
"BJA33HZH": "Probes/Lyman alpha/Tomography",
"AX4JTPEE": "Theory/Neutrinos",
"ZBYEE6PE": "Probes/CMB",
"CBMA6QNI": "Probes/CMB",
"9TJAJ6C8": "Methods/Field-level inference",
"AZP7JNYR": "Surveys/Other facilities",
"GDGK4KI2": "Probes/Peculiar velocities",
"N2DBY9DA": "Probes/Peculiar velocities",
"4FWLW6IZ": "Probes/Peculiar velocities",
"JK6PCG4D": "Methods/Field-level inference",
"T9LG68XV": "Resources/Reviews and lectures",
"QXXT49MM": "Resources/Reviews and lectures",
"R6LR4ITL": "Theory/Tensions and anomalies",
"LV36HW74": "Probes/Supernovae",
"F79T3SF3": "Probes/Peculiar velocities",
"4A28Q6VI": "Probes/Supernovae",
"YRS864BR": "Probes/Peculiar velocities",
"PWFYKK7R": "Probes/Lyman alpha/P1D",
"4CVTJ4DN": "Probes/Lyman alpha/IGM and absorbers",
"UDRI3TTD": "Probes/Lyman alpha/P1D",
"MYHGETCQ": "Surveys/Gaia and stellar",
"FCJ78SX5": "Surveys/Gaia and stellar",
"DWV4Z4MQ": "Surveys/Other facilities",
"2XANCKT6": "Resources/Reviews and lectures",
"RNL2KTN4": "Probes/Peculiar velocities",
"KI3QZSEE": "Surveys/DESI",
"QS8DWBA3": "Probes/Peculiar velocities",
"XMRFTQZ3": "Methods/Emulators and machine learning",
"Y26JHZZP": "Surveys/Other facilities",
"ZRLCLH47": "Probes/Peculiar velocities",
"8W56ARWF": "Probes/Supernovae",
"Y399INA7": "Probes/Galaxy clustering and BAO",
"XFIKW8DU": "Methods/Statistics and compression",
"UUX46XSL": "Methods/Statistics and compression",
"YUY42ZMJ": "Probes/Supernovae",
"A6XK5YLI": "Probes/Supernovae",
"UCBQZFWH": "Probes/Supernovae",
"THAJLU23": "Surveys/Gaia and stellar",
"E9Q72EBC": "Surveys/Gaia and stellar",
"GW5AWAED": "Probes/21 cm",
"2CP7J2BZ": "Probes/21 cm",
"EYYY9RX8": "Probes/Supernovae",
"HS3Z4N6M": "Surveys/Other facilities",
"ACJ9RHUV": "Probes/Supernovae",
"R2XK98Y5": "Probes/Lyman alpha/P1D",
"TABHY89Y": "Probes/Lyman alpha/P1D",
"FPT9CMLM": "Probes/Lyman alpha/P1D",
"79A8A7XS": "Methods/Field-level inference",
"E6W36KRS": "Probes/Peculiar velocities",
"JDVBMVEQ": "Probes/Lyman alpha/P1D",
"SYACFSLE": "Probes/Lyman alpha/P1D",
"6E3YDMHK": "Simulations/Hydrodynamical and IGM",
"Q7KKQWIQ": "Simulations/Hydrodynamical and IGM",
"SDHMMM52": "Probes/Supernovae",
"AJCGLA23": "Probes/Supernovae",
"7U3QGQZ5": "Probes/Weak lensing",
"LQA5G5SF": "Resources/Theses",
"EDYMMMSU": "Probes/Gravitational waves",
"M6VT2FER": "Probes/Peculiar velocities",
"GWK6L5JE": "Probes/Peculiar velocities",
"QDSIPTME": "Probes/Peculiar velocities",
"MPTKQ2KV": "Probes/Peculiar velocities",
"SKPGUVSG": "Resources/Theses",
"AX4PSIFG": "Methods/Field-level inference",
"HTB6W2FJ": "Methods/Field-level inference",
"SJ5LI76J": "Methods/Field-level inference",
"ZG8R9UJ6": "Methods/Field-level inference",
"AP5GUEZI": "Theory/Tensions and anomalies",
"P7R288WZ": "Theory/Tensions and anomalies",
"GF5I36N9": "Probes/Supernovae",
"723EN59J": "Probes/Supernovae",
"DMLTWTZ3": "Theory/Tensions and anomalies",
"I6XNJCTX": "Meta/Writing and community",
"R94ENEIZ": "Probes/Peculiar velocities",
"52TWLVTA": "Probes/Peculiar velocities",
"L7ALAWQP": "Probes/Weak lensing",
"GDIXR3WC": "Probes/Gravitational waves",
"V9CXCK5C": "Probes/Gravitational waves",
"XUNRCYEG": "Methods/Field-level inference",
"GNKUFMG3": "Methods/Field-level inference",
"TAG97WAZ": "Methods/Field-level inference",
"BM5MKKCB": "Methods/Field-level inference",
"N2YDQXA5": "Methods/Field-level inference",
"D88PUF4T": "Probes/Peculiar velocities",
"8GIHPU7Q": "Probes/Peculiar velocities",
"8F4SZXYQ": "Probes/Peculiar velocities",
"XLAWSD4W": "Methods/Field-level inference",
"T9U2EDLR": "Methods/Field-level inference",
"PVGZC5WE": "Probes/Supernovae",
"PXHL6N6T": "Probes/Peculiar velocities",
"RJNA5T9W": "Theory/Tensions and anomalies",
"RULGIY65": "Theory/Inflation and non-Gaussianity",
"432R7Z4W": "Resources/Reviews and lectures",
"D7PJ4IRE": "Theory/Inflation and non-Gaussianity",
"W8Z9JEWI": "Theory/Dark matter",
"J7BS2X28": "Theory/Dark energy",
"PPK3GKYX": "Theory/Dark matter",
"YWQ7D4HX": "Theory/Dark matter",
"UXV24JTH": "Theory/Dark matter",
"8LIE7QNN": "Theory/Dark matter",
"B5SMGEIZ": "Theory/Dark matter",
"4UTVJIQH": "Theory/Dark matter",
"W9SDK635": "Resources/Reviews and lectures",
"NILX9C9F": "Theory/Inflation and non-Gaussianity",
"GXK5DVLP": "Resources/Books",
"INJY5TTU": "Probes/Peculiar velocities",
"ZACF2HLT": "Theory/Foundations",
"3259EMJ5": "Theory/Dark energy",
"SRUP692B": "Theory/Dark energy",
"MQP6KNEL": "Theory/Dark energy",
"7CYBHMIF": "Theory/Foundations",
"3IS9NLDQ": "Theory/Foundations",
"IFM4T5GY": "Theory/Dark energy",
"ZEFCIMQG": "Theory/Dark energy",
"UUDNSBDQ": "Theory/Dark energy",
"MMNMRAPJ": "Theory/Dark energy",
"C337FIZ6": "Theory/Dark energy",
"364K7G4T": "Theory/Dark energy",
"RM6R6FUI": "Theory/Dark energy",
"PRPG74AY": "Theory/Modified gravity",
"IHI4LP94": "Theory/Modified gravity",
"STJVQZCS": "Theory/Dark matter"
}
};

// --------------------------------------------------------------- helpers
function log(s) { Zotero.debug(s); out.push(s); }
const out = [];

// existing collections, keyed by full path
function pathMap() {
  const all = Zotero.Collections.getByLibrary(LIB, true);
  const byID = {};
  all.forEach(c => byID[c.id] = c);
  const map = {};
  for (const c of all) {
    let parts = [c.name], p = c.parentID;
    while (p) { parts.unshift(byID[p].name); p = byID[p].parentID; }
    map[parts.join("/")] = c;
  }
  return map;
}

// --------------------------------------------------------- 1. hierarchy
let map = pathMap();
let created = 0;
for (const path of PAYLOAD.paths) {
  if (map[path]) continue;
  const parts = path.split("/");
  const name = parts.pop();
  const parentPath = parts.join("/");
  log((DRY_RUN ? "would create  " : "creating      ") + path);
  created++;
  if (!DRY_RUN) {
    const c = new Zotero.Collection();
    c.libraryID = LIB;
    c.name = name;
    if (parentPath) {
      if (!map[parentPath]) throw new Error("missing parent " + parentPath);
      c.parentID = map[parentPath].id;
    }
    await c.saveTx();
    map = pathMap();
  }
}

// ------------------------------------------------------------ 2. refile
let moved = 0, already = 0, missing = 0;
if (!DRY_RUN) map = pathMap();
for (const [key, path] of Object.entries(PAYLOAD.assign)) {
  const id = Zotero.Items.getIDFromLibraryAndKey(LIB, key);
  if (!id) { missing++; log("MISSING ITEM " + key); continue; }
  const item = Zotero.Items.get(id);
  const target = map[path];
  if (!target) { if (DRY_RUN) { moved++; continue; } throw new Error("no collection " + path); }
  const current = item.getCollections();
  if (current.length === 1 && current[0] === target.id) { already++; continue; }
  moved++;
  if (!DRY_RUN) {
    item.addToCollection(target.id);
    if (REMOVE_OLD) for (const cid of current) if (cid !== target.id) item.removeFromCollection(cid);
    await item.saveTx();
  }
}

// --------------------------------------------------- 3. empty old shells
let empties = [];
map = pathMap();
for (const [path, c] of Object.entries(map)) {
  if (PAYLOAD.paths.includes(path)) continue;
  if (c.getChildItems(true).length === 0 && c.getChildCollections(true).length === 0) {
    empties.push(path);
    if (DELETE_EMPTIED && !DRY_RUN) await c.eraseTx();
  }
}

log("");
log("collections created : " + created);
log("items refiled       : " + moved);
log("already correct     : " + already);
log("items not found     : " + missing);
log("old shells now empty: " + empties.length + (empties.length ? "  -> " + empties.join(", ") : ""));
log(DRY_RUN ? "\nDRY RUN -- nothing was written." : "\nApplied.");
return out.join("\n");
